### ISSUE TITLE
cast_site throws error

### ISSUE THREAD

**Issue by brodjieski** [skorokithakis/catt#121]
When trying to cast a URL, it produces the following error.  Any idea what I might be missing?

```
catt cast_site "http://www.google.com"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/pi/.local/lib/python3.5/site-packages/pychromecast/socket_client.py", line 341, in run
    if self.run_once() == 1:
  File "/home/pi/.local/lib/python3.5/site-packages/pychromecast/socket_client.py", line 406, in run_once
    function(data)
  File "/home/pi/.local/lib/python3.5/site-packages/pychromecast/socket_client.py", line 830, in <lambda>
    self._block_till_launched(app_id))
  File "/home/pi/.local/lib/python3.5/site-packages/pychromecast/socket_client.py", line 843, in _block_till_launched
    app_id, self.launch_failure.reason))
pychromecast.error.LaunchError: Failed to launch app: 84912283, Reason: NOT_FOUND

```

**Comment by brodjieski** [comment]
NVM... just realized my pi-hole was blocking access to the dash cast....
