### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by CodeFestus** [skorokithakis/catt#159]
I was having some youtube issues so I did a pip install --upgrade catt...and got these:

ImportError: No module named configparser
ImportError: No module named pathlib

And then:
$ catt --help
Traceback (most recent call last):
  File "/home/nook/.local/bin/catt", line 7, in <module>
    from catt.cli import main
  File "/home/nook/.local/lib/python2.7/site-packages/catt/cli.py", line 13, in <module>
    from .controllers import Cache, CastState, StateFileError, StateMode, get_chromecast, get_chromecasts, setup_cast
  File "/home/nook/.local/lib/python2.7/site-packages/catt/controllers.py", line 189
    def set_data(self, *args) -> None:
                              ^
SyntaxError: invalid syntax

**Comment by skorokithakis** [comment]
You need Python 3, I'm afraid.
