### ISSUE TITLE
Casting local files broken in 0.9.1

### ISSUE THREAD

**Issue by mellbye** [skorokithakis/catt#164]
It looks like casting local files broke with the 0.9.1 release:

```
Traceback (most recent call last):
  File "~/.local/bin/catt", line 10, in <module>
    sys.exit(main())
  File "~/.local/lib/python3.7/site-packages/catt/cli.py", line 472, in main
    return cli(obj={}, default_map=readconfig())
  File "~/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "~/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "~/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "~/.local/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "~/.local/lib/python3.7/site-packages/catt/cli.py", line 169, in cast
    settings["device"], video_url=video_url, prep="app", controller=controller, ytdl_options=ytdl_option
  File "~/.local/lib/python3.7/site-packages/catt/controllers.py", line 139, in setup_cast
    app = get_app("default")
  File "~/.local/lib/python3.7/site-packages/catt/controllers.py", line 107, in get_app
    raise AppSelectionError("cast_type is needed for app selection")
catt.controllers.AppSelectionError: cast_type is needed for app selection
```

It seems like local casting calls `get_app("default")`, which was previously special-cased inside `get_app`.

**Comment by theychx** [comment]
Thank you for reporting this. We'll roll out a new release ASAP.

**Comment by skorokithakis** [comment]
0.9.2 is out and (hopefully) fixes this, thanks!
