### ISSUE TITLE
DefaultCastController object has no attribute clear

### ISSUE THREAD

**Issue by ArtBIT** [skorokithakis/catt#175]
In v0.9.2, when I run:
```
catt clear
```

I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/catt", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/catt/cli.py", line 472, in main
    return cli(obj={}, default_map=readconfig())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/catt/cli.py", line 256, in clear
    cst.clear()
AttributeError: 'DefaultCastController' object has no attribute 'clear'
```

**Comment by theychx** [comment]
That's an oversight on my part, but should be an easy fix.
Thank you for reporting this!

@skorokithakis Maybe we should also include ```(YouTube only)``` in the shorthelp of the relevant cmds, to avoid unnecessary confusion.

**Comment by skorokithakis** [comment]
@theychx Yes, for the YT-only commands we should definitely do that.
