### ISSUE TITLE
Traceback error 

### ISSUE THREAD

**Issue by kingmoe001** [skorokithakis/catt#182]
Traceback (most recent call last):
  File "/usr/local/bin/catt", line 6, in <module>
    from catt.cli import main
  File "/usr/local/lib/python2.7/dist-packages/catt/cli.py", line 7, in <module>
    from pathlib import Path
ImportError: No module named pathlib
________________________________
What can I do to fix this??

**Comment by theychx** [comment]
`catt` needs python 3.
