### ISSUE TITLE
catt crashes when trying to cast youtube

### ISSUE THREAD

**Issue by pizzadude** [skorokithakis/catt#2]
```
pizzadude@pizzadude-thinkpad ~ $ catt cast https://www.youtube.com/watch?v=1sTHTdLaSjM
[youtube] 1sTHTdLaSjM: Downloading webpage
[youtube] 1sTHTdLaSjM: Downloading video info webpage
[youtube] 1sTHTdLaSjM: Extracting video information
[youtube] 1sTHTdLaSjM: Downloading MPD manifest
Traceback (most recent call last):
  File "/usr/local/bin/catt", line 9, in <module>
    load_entry_point('catt==0.2.0', 'console_scripts', 'catt')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/catt/cli.py", line 19, in cast
    stream_info = get_stream_info(video_url)
  File "/usr/local/lib/python2.7/dist-packages/catt/controllers.py", line 15, in get_stream_info
    best_format = list(format_selector(info["formats"]))[0]
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1057, in selector_function
    for format in f(ctx):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1075, in selector_function
    formats = list(ctx['formats'])
TypeError: list indices must be integers, not unicode
```
This is on Linux Mint 18 (Ubuntu 16.04)

**Comment by skorokithakis** [comment]
Does it crash for all videos? That URL works fine for me...

**Comment by pizzadude** [comment]
>Does it crash for all videos? That URL works fine for me...

Yes, it does.

**Comment by skorokithakis** [comment]
Hmm, what version are you running? It looks like `ctx` there is a list, rather than a dict, which is weird.

**Comment by pizzadude** [comment]
0.2.0 installed using pip install catt

**Comment by skorokithakis** [comment]
Hmm, that's the latest version. Unfortunately, I can't reproduce it, so I don't know how to fix it :/ That video works perfectly for me. Do you have more than one chromecasts, maybe?

**Comment by theychx** [comment]
Something changed with youtube-dl's inner-workings as of version `2016.07.16`, which I think is causing this. This is probably the culprit:  [https://github.com/rg3/youtube-dl/commit/317f7ab634174666e458807fa309a2e7ba459267](url)

@pizzadude 
A temporary fix would be to revert to youtube-dl version `2016.07.13`

**Comment by skorokithakis** [comment]
Ah, good call, I didn't try updating my dependencies. Let me do that and revert if necessary.

**Comment by pizzadude** [comment]
>A temporary fix would be to revert to youtube-dl version 2016.07.13

That fixed it. (for now) Thanks!

**Comment by skorokithakis** [comment]
I can reproduce, thank you for the info, @theychx.
