### ISSUE TITLE
latest fails to build

### ISSUE THREAD

**Issue by atomi** [skorokithakis/catt#21]
```
Collecting git+https://github.com/skorokithakis/catt
  Cloning https://github.com/skorokithakis/catt to /tmp/pip-l_sty7jq-build
Requirement already up-to-date: youtube-dl>=2016.07.13 in /usr/local/lib/python3.5/dist-packages (from catt==0.4.2)
Requirement already up-to-date: PyChromecast==0.7.7 in /usr/local/lib/python3.5/dist-packages (from catt==0.4.2)
Requirement already up-to-date: Click>=5.0 in /usr/local/lib/python3.5/dist-packages (from catt==0.4.2)
Requirement already up-to-date: six>=1.10.0 in /usr/lib/python3/dist-packages (from PyChromecast==0.7.7->catt==0.4.2)
Requirement already up-to-date: protobuf==3.0.0b2 in /usr/local/lib/python3.5/dist-packages (from PyChromecast==0.7.7->catt==0.4.2)
Requirement already up-to-date: zeroconf>=0.17.4 in /usr/local/lib/python3.5/dist-packages (from PyChromecast==0.7.7->catt==0.4.2)
Requirement already up-to-date: requests>=2.0 in /usr/local/lib/python3.5/dist-packages (from PyChromecast==0.7.7->catt==0.4.2)
Requirement already up-to-date: setuptools in /usr/local/lib/python3.5/dist-packages (from protobuf==3.0.0b2->PyChromecast==0.7.7->catt==0.4.2)
Requirement already up-to-date: netifaces in /usr/local/lib/python3.5/dist-packages (from zeroconf>=0.17.4->PyChromecast==0.7.7->catt==0.4.2)
Requirement already up-to-date: enum-compat in /usr/local/lib/python3.5/dist-packages (from zeroconf>=0.17.4->PyChromecast==0.7.7->catt==0.4.2)
Requirement already up-to-date: packaging>=16.8 in /usr/local/lib/python3.5/dist-packages (from setuptools->protobuf==3.0.0b2->PyChromecast==0.7.7->catt==0.4.2)
Collecting appdirs>=1.4.0 (from setuptools->protobuf==3.0.0b2->PyChromecast==0.7.7->catt==0.4.2)
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Collecting pyparsing (from packaging>=16.8->setuptools->protobuf==3.0.0b2->PyChromecast==0.7.7->catt==0.4.2)
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 4.9MB/s 
Installing collected packages: catt, appdirs, pyparsing
  Found existing installation: catt 0.4.2
    Uninstalling catt-0.4.2:
      Successfully uninstalled catt-0.4.2
  Running setup.py install for catt ... done
  Found existing installation: appdirs 1.4.2
    Uninstalling appdirs-1.4.2:
      Successfully uninstalled appdirs-1.4.2
  Rolling back uninstall of appdirs
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2813, in _dep_map
    return self.__dep_map
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2624, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2804, in _parsed_pkg_info
    return self._pkg_info
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2624, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip-9.0.1-py3.5.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip-9.0.1-py3.5.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.5/dist-packages/pip-9.0.1-py3.5.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/pip-9.0.1-py3.5.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.5/dist-packages/pip-9.0.1-py3.5.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.5/dist-packages/pip-9.0.1-py3.5.egg/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/local/lib/python3.5/dist-packages/pip-9.0.1-py3.5.egg/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 320, in __init__
    _Distribution.__init__(self, attrs)
  File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 386, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2324, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 862, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2568, in requires
    dm = self._dep_map
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2815, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2824, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2806, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1468, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1577, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/appdirs-1.4.2.dist-info/METADATA'
```

**Comment by skorokithakis** [comment]
Looks like an appdirs problem? I can't reproduce this, I'm afraid.

**Comment by atomi** [comment]
@skorokithakis yeah thanks.

Fix is upgrading appdirs to latest
`pip install --upgrade appdirs`

**Comment by atomi** [comment]
By the way, this runs great on termux android with youtube-dl. thanks for the great software!

**Comment by skorokithakis** [comment]
Thank you, I'm glad you like it!
