### ISSUE TITLE
cast_site error when using info

### ISSUE THREAD

**Issue by mrevjd** [skorokithakis/catt#214]
Hi There,

First of all, what a wonder app.

If I'm using cast_site and request info or status I receive the following error:
Traceback (most recent call last):
  File "/usr/local/bin/catt", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/catt/cli.py", line 495, in main
    return cli(obj={}, default_map=readconfig())
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/catt/cli.py", line 335, in status
    cst = setup_cast(settings["device"], prep="info")
  File "/usr/local/lib/python3.6/dist-packages/catt/controllers.py", line 173, in setup_cast
    cast_controller = get_controller(cast, app, action=action, prep=prep)
  File "/usr/local/lib/python3.6/dist-packages/catt/controllers.py", line 146, in get_controller
    return controller(cast, app, prep=prep)
  File "/usr/local/lib/python3.6/dist-packages/catt/controllers.py", line 589, in __init__
    super(DashCastController, self).__init__(cast, app, prep=prep)
  File "/usr/local/lib/python3.6/dist-packages/catt/controllers.py", line 372, in __init__
    self.prep_info()
  File "/usr/local/lib/python3.6/dist-packages/catt/controllers.py", line 393, in prep_info
    self._update_status()
  File "/usr/local/lib/python3.6/dist-packages/catt/controllers.py", line 409, in _update_status
    update()
  File "/usr/local/lib/python3.6/dist-packages/catt/controllers.py", line 406, in update
    self._cast.media_controller.update_status()
  File "/usr/local/lib/python3.6/dist-packages/pychromecast/controllers/media.py", line 350, in update_status
    {MESSAGE_TYPE: TYPE_GET_STATUS}, callback_function=callback_function_param
  File "/usr/local/lib/python3.6/dist-packages/pychromecast/controllers/__init__.py", line 86, in send_message
    self.namespace
pychromecast.error.UnsupportedNamespace: Namespace urn:x-cast:com.google.cast.media is not supported by runningapplication.

Commands run:
catt -d "10.254.0.10" cast_site https://www.google.com.au
catt -d 10.254.0.10 status
catt -d 10.254.0.10 info

Versions:
Python 3.6.8
catt v0.10.0, Winter Waterfall.
Ubuntu 18.04.3 LTS

Cheers

**Comment by mrevjd** [comment]
Found some out dated libraries and an update resolved it.

**Comment by mrevjd** [comment]
Sorry I closed the wrong Issue.

**Comment by theychx** [comment]
Yep, that's a bug. You're supposed to get this error message:
```
Error: This action is not supported by the dashcast controller.
```

Thank you for reporting this!

**Comment by mrevjd** [comment]
Wow that was a quick fix and turn around.
Cheers
