### ISSUE TITLE
set_default Doesn't Create Directory

### ISSUE THREAD

**Issue by gwnichol** [skorokithakis/catt#251]
Catt `set_default` is unable to create the config file in `~/.config/catt` when `~/.config` does not exist. After manually creating the `~/.config` directory, it works.

The full stack trace is as follows, but the issue is pretty easy to track.
```
Traceback (most recent call last):
  File "/home/gwnichol/.local/bin/catt", line 10, in <module>
    sys.exit(main())
  File "/home/gwnichol/.local/lib/python3.7/site-packages/catt/cli.py", line 570, in main
    return cli(obj={}, default_map=get_default_map())
  File "/home/gwnichol/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/gwnichol/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/gwnichol/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gwnichol/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gwnichol/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/gwnichol/.local/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/gwnichol/.local/lib/python3.7/site-packages/catt/cli.py", line 472, in set_default
    writeconfig(config)
  File "/home/gwnichol/.local/lib/python3.7/site-packages/catt/cli.py", line 535, in writeconfig
    CONFIG_DIR.mkdir()
  File "/usr/lib/python3.7/pathlib.py", line 1251, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/gwnichol/.config/catt'
```

**Comment by theychx** [comment]
Thank you for reporting this!

**Comment by skorokithakis** [comment]
I've issued a PR to fix this, but can I ask how come your config dir doesn't exist?

**Comment by gwnichol** [comment]
> I've issued a PR to fix this, but can I ask how come your config dir doesn't exist?

Lol, I'm on a new headless rasphian install with a new user, very few programs are installed and none have created the dir.

**Comment by skorokithakis** [comment]
Ah, that makes sense, thanks. In any case, this fix has been merged, can you verify that it works for you?

**Comment by gwnichol** [comment]
Yes, it now works for me. Thank You
