### ISSUE TITLE
youtube_dl.utils.ExtractorError: Unsupported JS expression '[null,'; please report this issue on

### ISSUE THREAD

**Issue by sentriz** [skorokithakis/catt#257]
Hi! thanks for the project

I get this error a few times a day for the past couple months

```
$ catt cast "https://www.youtube.com/watch?v=jvcdnF2ZRUI"                                                                                                      master dirty
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/senan/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1379, in _decrypt_signature
    func = self._extract_signature_function(
  File "/home/senan/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1293, in _extract_signature_function
    cache_res = res(test_string)
  File "/home/senan/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1356, in <lambda>
    return lambda s: initial_function([s])
  File "/home/senan/.local/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/home/senan/.local/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/senan/.local/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 91, in interpret_expression
    right_val = self.interpret_expression(
  File "/home/senan/.local/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 188, in interpret_expression
    x, abort = self.interpret_statement(
  File "/home/senan/.local/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/senan/.local/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '[null,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '[null,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Error: Remote resource not found.
```

and 

```
$ youtube-dl --version                                                                                                                                        
2020.03.24
$ catt --version                                                                                                                                               
catt v0.11.0, Yearning Yachtman.
```
note just "youtube-dl" the with same url as an argument works

thanks!

**Comment by skorokithakis** [comment]
Hmm, this seems like a youtube-dl error, it doesn't look like something specific to catt. Does youtube-dl work all day, or also just sometimes?

**Comment by sentriz** [comment]
heh it just started working again when I tried it out. i'll post here the next time it happens

**Comment by skorokithakis** [comment]
Even if you do, I'm not sure we can really do anything about a youtube-dl error... I'll close this for now, please post again if it turns out to be a catt error, thanks!

**Comment by theychx** [comment]
@sentriz 
Just out of curiosity, can you try:
```
which youtube-dl
```
and then check the shebang of the file that `which` output. You might have the current `youtube-dl` installed for python2, and an outdated version for python3 (which would be the one that `catt` is using).
I recognized the traceback, and this issue was fixed many months back.

**Comment by sentriz** [comment]
intesting. i don't have python2 on my system (`python` is a symlink to `python3`), but there was a difference in the binary in my path and the library
![](https://i.imgur.com/DQT33fm.png)
thanks! i'll see if it makes a difference
