### ISSUE TITLE
Pychromecasts last release breaks casting

### ISSUE THREAD

**Issue by sickmartian** [skorokithakis/catt#271]
Seems like since the last release get_chromecasts will return a tuple: https://github.com/home-assistant-libs/pychromecast/commit/e8d04cd9a12b4f434f69a98f2eb03d44fbc302ae

Breaking change: https://github.com/home-assistant-libs/pychromecast/blob/e8d04cd9a12b4f434f69a98f2eb03d44fbc302ae/pychromecast/__init__.py#L161

Might be good to cap the version of the library to 6.x

It generates the following error for me:
```Traceback (most recent call last):
  File "/usr/local/bin/catt", line 11, in <module>
    sys.exit(main())
  File "/home/osmc/.local/lib/python3.6/site-packages/catt/cli.py", line 570, in main
    return cli(obj={}, default_map=get_default_map())
  File "/home/osmc/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/osmc/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/osmc/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/osmc/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/osmc/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/osmc/.local/lib/python3.6/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/osmc/.local/lib/python3.6/site-packages/catt/cli.py", line 165, in cast
    settings["device"], video_url=video_url, prep="app", controller=controller, ytdl_options=ytdl_option
  File "/home/osmc/.local/lib/python3.6/site-packages/catt/controllers.py", line 144, in setup_cast
    cast, cc_info = get_cast(device_name)
  File "/home/osmc/.local/lib/python3.6/site-packages/catt/controllers.py", line 92, in get_cast
    cache = Cache()
  File "/home/osmc/.local/lib/python3.6/site-packages/catt/controllers.py", line 222, in __init__
    devices = get_chromecasts()
  File "/home/osmc/.local/lib/python3.6/site-packages/catt/controllers.py", line 45, in get_chromecasts
    devices.sort(key=lambda cc: cc.name)```

**Comment by xXAnToS12Xx** [comment]
Let's hope it gets updated soon

**Comment by skorokithakis** [comment]
@xXAnToS12Xx can you use the latest master and see if that solves your problem?

I'm assuming we should probably make a new release, as this breaks things for people.

**Comment by nobodywasishere** [comment]
Doing `make install` from master works for me with none of the dependencies originally installed (I can see it grabs them as part of the install process). Do you know when there will be a new release?

**Comment by skorokithakis** [comment]
This was released months ago, what's broken for you?

**Comment by nobodywasishere** [comment]
Ah apologies misread the dates. I noticed earlier that the AUR package for catt has been orphaned and was looking into bringing it up to date. What's actually wrong is a bunch of arch silliness, and will be fixed after [this AUR package](https://aur.archlinux.org/packages/python-pychromecast6/) is fixed and someone updates the requirements of the catt PKGBUILD. 

Nothing for you to worry about though (and honestly understand if you don't care at all - it's just easier to get this kind of stuff from pip). I misread what you said as pushing a release for pychromecast 7 support, which isn't the case. Thank you!

**Comment by skorokithakis** [comment]
Ah, not yet, #277 is open, though we aren't in a rush since 6 still works. Thanks!
