### ISSUE TITLE
cast or status doesnt work

### ISSUE THREAD

**Issue by Mr-KyD** [skorokithakis/catt#273]
Hi!

OS : Gentoo Linux
Python : 3.9

When i try to cast something or made and status ( catt cast URL or catt status ) i get : 

```
Traceback (most recent call last):
File ".local/share/virtualenvs/cast-MojTnEDo/bin/catt", line 8, in <module>
sys.exit(main())
File ".local/share/virtualenvs/cast-MojTnEDo/lib/python3.9/site-packages/catt/cli.py", line 570, in main
return cli(obj={}, default_map=get_default_map())
File ".local/share/virtualenvs/cast-MojTnEDo/lib/python3.9/site-packages/click/core.py", line 829, in call
return self.main(args, kwargs)
File ".local/share/virtualenvs/cast-MojTnEDo/lib/python3.9/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File ".local/share/virtualenvs/cast-MojTnEDo/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File ".local/share/virtualenvs/cast-MojTnEDo/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, ctx.params)
File ".local/share/virtualenvs/cast-MojTnEDo/lib/python3.9/site-packages/click/core.py", line 610, in invoke
return callback(args, kwargs)
File ".local/share/virtualenvs/cast-MojTnEDo/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
return f(get_current_context().obj, *args, kwargs)
File ".local/share/virtualenvs/cast-MojTnEDo/lib/python3.9/site-packages/catt/cli.py", line 366, in status
cst = setup_cast(settings["device"], prep="info")
File ".local/share/virtualenvs/cast-MojTnEDo/lib/python3.9/site-packages/catt/controllers.py", line 144, in setup_cast
cast, cc_info = get_cast(device_name)
File ".local/share/virtualenvs/cast-MojTnEDo/lib/python3.9/site-packages/catt/controllers.py", line 96, in get_cast
cast = get_chromecast_with_ip(cc_info.ip, cc_info.port)
File ".local/share/virtualenvs/cast-MojTnEDo/lib/python3.9/site-packages/catt/controllers.py", line 67, in get_chromecast_with_ip
return pychromecast.Chromecast(device_ip, port=port, tries=1)
File ".local/share/virtualenvs/cast-MojTnEDo/lib/python3.9/site-packages/pychromecast/init.py", line 296, in init
self.device = get_device_status(self.host, services, zconf)
File ".local/share/virtualenvs/cast-MojTnEDo/lib/python3.9/site-packages/pychromecast/dial.py", line 75, in get_device_status
status = _get_status(host, services, zconf, "/setup/eureka_info?options=detail")
File ".local/share/virtualenvs/cast-MojTnEDo/lib/python3.9/site-packages/pychromecast/dial.py", line 41, in _get_status
for service in services.copy():
AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by dtheyer** [comment]
I'm getting the same error on Ubuntu 18.04 with python version 3.6.9

**Comment by skorokithakis** [comment]
Hm, this is non-good... I'm going to need to debug this tomorrow, as it's very late here now... Maybe @theychx knows something about this?

**Comment by skorokithakis** [comment]
@dtheyer can you print the discovered cc_info to see which one's ip is None?

**Comment by dtheyer** [comment]
Here is the output from printing cc_info.all_info 

`{'ip': None, 'port': 8009, 'manufacturer': 'Google Inc.', 'model_name': 'Google Nest Hub', 'cast_type': 'cast'}
`

**Comment by theychx** [comment]
PyChromecast is broken, as far as I can tell. I'll investigate further, later today.

**Comment by skorokithakis** [comment]
Hmm, it's odd that it seems to be picking up the Nest hub, but it looks like we can safely ignore devices with no IP. Unfortunately, I don't have a Nest hub to test (or even any Chromecast devices on my current subnet).

@theychx, if you can investigate, that'd be great, otherwise I vote we check that `cc_info.ip is not None`, which seems like it shouldn't give us other problems.

**Comment by skorokithakis** [comment]
PyChromecast 7 has started tracking devices by UUID instead of mDNS name, but it doesn't look like it's relevant to the bug here, at first glance.

**Comment by kalkun** [comment]
PyChromecast 7 doesnt provide the host.
Calling e.g. `pychromecast.get_chromecasts`

**Comment by kalkun** [comment]
I have made [this PR to pychromecast](https://github.com/home-assistant-libs/pychromecast/pull/383) which fixed the issue for me.

**Comment by skorokithakis** [comment]
It looks like the workaround they mention will work, or we can use their `socket_client`. Unfortunately discovery won't work for me because of how my network is set up, so it will be a few days/weeks before I can get to a network where I can reproduce this...

**Comment by benklaasen** [comment]
> I'm getting the same error on Ubuntu 18.04 with python version 3.6.9
> 
> Seems like the problem is due to calling get_chromecast_with_ip() in controllers.py with device_ip=None.
> 
> Adding an additional check to get_cast() seems to fix this bug for me.
> 
> I changed line 95 in controllers.py from:
> `if cc_info: `
> to:
> `if cc_info and cc_info.ip: `

I tried the fix mentioned by @dtheyer above, with the following result:

```
$ catt cast 'https://m.youtube.com/watch?v=8PKn4O2KVwA'
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/catt", line 8, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/catt/cli.py", line 570, in main
    return cli(obj={}, default_map=get_default_map())
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/catt/cli.py", line 164, in cast
    cst, stream = setup_cast(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/catt/controllers.py", line 146, in setup_cast
    stream = StreamInfo(video_url, device_info=cc_info, ytdl_options=ytdl_options) if video_url else None
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/catt/stream_info.py", line 34, in __init__
    self.local_ip = get_local_ip(device_info.ip) if device_info else None
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/catt/util.py", line 94, in get_local_ip
    host_ipversion = type(ipaddress.ip_address(host))
  File "/data/data/com.termux/files/usr/lib/python3.8/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: None does not appear to be an IPv4 or IPv6 address
```

As you can see, I'm using Termux, which I hope isn't too esoteric.

`catt scan` returns:
```
Scanning Chromecasts...
None - Big Telly TV - Google Inc. Chromecast
```

'Port Authority' running on the same device locates the Chromecast at 192.168.1.115. I'm not using IPv6 on my network.

**Comment by skorokithakis** [comment]
baloob's comment in https://github.com/home-assistant-libs/pychromecast/pull/383#issuecomment-652046503 is very interesting, if all we need is the IP we can just use zeroconf and avoid the heavy pychromecast dependency, although we use it for the controllers as well... Hmm.

**Comment by skorokithakis** [comment]
Can you try 0.11.2? I have reverted the 7 compatibility fix and pinned to PyChromecast 6 to avoid a broken release until we can figure out what to do with the dependency.

**Comment by KentEkl** [comment]
It works again from Hassio with my Google Nest hub after your latest changes.

arch | x86_64
chassis | vm
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.10
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.44
python_version | 3.7.7
supervisor | 228
timezone | Europe/Stockholm
version | 0.112.0b3
virtualenv | false

**Comment by benklaasen** [comment]
That's phenomenal, thank you. Working beautifully now on Termux too:

```
[u0_a114@localhost:~]$ !catt
catt scan
Scanning Chromecasts...
192.168.1.115 - Big Telly TV - Google Inc. Chromecast
[u0_a114@localhost:~]$ catt cast 'https://m.youtube.com/watch?v=8PKn4O2KVwA'
Casting remote file https://m.youtube.com/watch?v=8PKn4O2KVwA...
Playing "DPReview TV: Olympus OM-D E-M5 III - worth the wait?" on "Big Telly TV"...
[u0_a114@localhost:~]$ catt pause
[u0_a114@localhost:~]$
```

**Comment by skorokithakis** [comment]
Fantastic, thanks!
