### ISSUE TITLE
error from a system update 

### ISSUE THREAD

**Issue by scooper1** [skorokithakis/catt#324]
any clue for this error
using with home assistant and web terminal  
error with  python 3.8 ????
catt --version
catt v0.12.0, Zaniest Zapper.

catt scan       
Scanning Chromecasts...
Traceback (most recent call last):
  File "/usr/bin/catt", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/catt/cli.py", line 641, in main
    return cli(obj=get_config_as_dict())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/catt/cli.py", line 482, in scan
    devices = get_cast_devices_info()
  File "/usr/lib/python3.8/site-packages/catt/discovery.py", line 63, in get_cast_devices_info
    devices = get_cast_devices()
  File "/usr/lib/python3.8/site-packages/catt/discovery.py", line 50, in get_cast_devices
    devices = [CastDevice(pychromecast.get_chromecast_from_service(s, browser.zc), s[4], s[5]) for s in services]
  File "/usr/lib/python3.8/site-packages/catt/discovery.py", line 50, in <listcomp>
    devices = [CastDevice(pychromecast.get_chromecast_from_service(s, browser.zc), s[4], s[5]) for s in services]
AttributeError: module 'pychromecast' has no attribute 'get_chromecast_from_service'

**Comment by skorokithakis** [comment]
It sounds like a wrong installation, I'm afraid I don't know what you could do to fix this. Probably just reinstall catt, I'd say.

**Comment by scooper1** [comment]
done reinstall may times with both a machine and router reboot and reset all the cast devices
would appreciate so help in tracking down the problem
i am using this from a home assistant  terminal it been working ok but lastest beta has broken this - if i can work out why i try to fix 
quite a few people use catt in this manor

**Comment by skorokithakis** [comment]
Try this:

```
pip uninstall catt pychromecast
pip install catt
```

**Comment by scooper1** [comment]
same error
think it may to be to do with latest python library as the system has been doing small changes to cope with that library  
```
pip uninstall catt pychromecast
Found existing installation: catt 0.12.0
Uninstalling catt-0.12.0:
  Would remove:
    /usr/bin/catt
    /usr/lib/python3.8/site-packages/catt-0.12.0.dist-info/*
    /usr/lib/python3.8/site-packages/catt/*
Proceed (y/n)? y
  Successfully uninstalled catt-0.12.0
Found existing installation: PyChromecast 9.0.0
Uninstalling PyChromecast-9.0.0:
  Would remove:
    /usr/lib/python3.8/site-packages/PyChromecast-9.0.0.dist-info/*
    /usr/lib/python3.8/site-packages/pychromecast/*
Proceed (y/n)? y
  Successfully uninstalled PyChromecast-9.0.0
➜  ~ pip install catt              
Collecting catt
  Using cached catt-0.12.0-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: requests>=2.23.0 in /usr/lib/python3.8/site-packages (from catt) (2.25.1)
Requirement already satisfied: Click>=7.1.2 in /usr/lib/python3.8/site-packages (from catt) (7.1.2)
Collecting PyChromecast>=7.5.0
  Using cached PyChromecast-9.0.0-py2.py3-none-any.whl (61 kB)
Requirement already satisfied: ifaddr>=0.1.7 in /usr/lib/python3.8/site-packages (from catt) (0.1.7)
Requirement already satisfied: youtube-dl>=2020.9.20 in /usr/lib/python3.8/site-packages (from catt) (2021.2.22)
Requirement already satisfied: zeroconf>=0.25.1 in /usr/lib/python3.8/site-packages (from PyChromecast>=7.5.0->catt) (0.28.8)
Requirement already satisfied: casttube>=0.2.0 in /usr/lib/python3.8/site-packages (from PyChromecast>=7.5.0->catt) (0.2.1)
Requirement already satisfied: protobuf>=3.0.0 in /usr/lib/python3.8/site-packages (from PyChromecast>=7.5.0->catt) (3.15.3)
Requirement already satisfied: six>=1.9 in /usr/lib/python3.8/site-packages (from protobuf>=3.0.0->PyChromecast>=7.5.0->catt) (1.15.0)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/lib/python3.8/site-packages (from requests>=2.23.0->catt) (3.0.4)
Requirement already satisfied: idna<3.2,>=2.5 in /usr/lib/python3.8/site-packages (from requests>=2.23.0->catt) (3.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.8/site-packages (from requests>=2.23.0->catt) (1.26.2)
Installing collected packages: PyChromecast, catt
Successfully installed PyChromecast-9.0.0 catt-0.12.0
➜  ~ catt scan                      
Scanning Chromecasts...
Traceback (most recent call last):
  File "/usr/bin/catt", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/catt/cli.py", line 641, in main
    return cli(obj=get_config_as_dict())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/catt/cli.py", line 482, in scan
    devices = get_cast_devices_info()
  File "/usr/lib/python3.8/site-packages/catt/discovery.py", line 63, in get_cast_devices_info
    devices = get_cast_devices()
  File "/usr/lib/python3.8/site-packages/catt/discovery.py", line 50, in get_cast_devices
    devices = [CastDevice(pychromecast.get_chromecast_from_service(s, browser.zc), s[4], s[5]) for s in services]
  File "/usr/lib/python3.8/site-packages/catt/discovery.py", line 50, in <listcomp>
    devices = [CastDevice(pychromecast.get_chromecast_from_service(s, browser.zc), s[4], s[5]) for s in services]
AttributeError: module 'pychromecast' has no attribute 'get_chromecast_

```

**Comment by scooper1** [comment]
the pychromecast was updated to version 9.0.0   Released: Feb 26, 2021
I think that maybe the issue

**Comment by scooper1** [comment]
i can confirm issue is pychromecast 9.0.0  version 8.1.2  works ok 
i think this issue needs to be reopened  
thanks

**Comment by skorokithakis** [comment]
Hmm, PyChromecast 9 works for me... That's very odd...

**Comment by scooper1** [comment]
i have the issue both sites i have access to if there are any chrome cast devices online it errors out

**Comment by borwolf** [comment]
Same problem here.

**Comment by heartkingz** [comment]
Same issue here.

**Comment by francois-nitenberg** [comment]
Same issue for me on my desktop (macos) and home assistant OS (rpi4).

For now I have downgraded the dependency and it resolves the issue:

```
pip uninstall pychromecast
pip install 'pychromecast<9.0.0
```

Output:
```
Collecting pychromecast<9.0.0
  Downloading PyChromecast-8.1.2-py2.py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB 2.8 MB/s
```

**Comment by skorokithakis** [comment]
Can you try and see if the latest master resolves this?

**Comment by francois-nitenberg** [comment]
Commit [2cd45525347258e52a89abec87d1a21cdb60f445](https://github.com/skorokithakis/catt/commit/2cd45525347258e52a89abec87d1a21cdb60f445 ) seems to solve the dependency issue, PyChromecast 8.1.2 is pulled down instead of latest 9.0.0.

```
pip install git+https://github.com/skorokithakis/catt.git
Collecting git+https://github.com/skorokithakis/catt.git
  Cloning https://github.com/skorokithakis/catt.git to /private/var/folders/jq/ll6v5k116mz_7c01py44dc6m0000gn/T/pip-req-build-pzwcxyfe
  Running command git clone -q https://github.com/skorokithakis/catt.git /private/var/folders/jq/ll6v5k116mz_7c01py44dc6m0000gn/T/pip-req-build-pzwcxyfe
Requirement already satisfied: youtube-dl>=2020.9.20 in ./.pyenv/versions/3.8.5/lib/python3.8/site-packages (from catt==0.12.0) (2021.2.22)
Collecting PyChromecast<9,>=8.0.0
  Using cached PyChromecast-8.1.2-py2.py3-none-any.whl (59 kB)
Requirement already satisfied: Click<8,>=7.1.2 in ./.pyenv/versions/3.8.5/lib/python3.8/site-packages (from catt==0.12.0) (7.1.2)
Requirement already satisfied: ifaddr>=0.1.7 in ./.pyenv/versions/3.8.5/lib/python3.8/site-packages (from catt==0.12.0) (0.1.7)
Requirement already satisfied: requests>=2.23.0 in ./.pyenv/versions/3.8.5/lib/python3.8/site-packages (from catt==0.12.0) (2.24.0)
Requirement already satisfied: zeroconf>=0.25.1 in ./.pyenv/versions/3.8.5/lib/python3.8/site-packages (from PyChromecast<9,>=8.0.0->catt==0.12.0) (0.28.8)
Requirement already satisfied: casttube>=0.2.0 in ./.pyenv/versions/3.8.5/lib/python3.8/site-packages (from PyChromecast<9,>=8.0.0->catt==0.12.0) (0.2.1)
Requirement already satisfied: protobuf>=3.0.0 in ./.pyenv/versions/3.8.5/lib/python3.8/site-packages (from PyChromecast<9,>=8.0.0->catt==0.12.0) (3.15.3)
Requirement already satisfied: six>=1.9 in ./.pyenv/versions/3.8.5/lib/python3.8/site-packages (from protobuf>=3.0.0->PyChromecast<9,>=8.0.0->catt==0.12.0) (1.15.0)
Requirement already satisfied: chardet<4,>=3.0.2 in ./.pyenv/versions/3.8.5/lib/python3.8/site-packages (from requests>=2.23.0->catt==0.12.0) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./.pyenv/versions/3.8.5/lib/python3.8/site-packages (from requests>=2.23.0->catt==0.12.0) (1.25.10)
Requirement already satisfied: certifi>=2017.4.17 in ./.pyenv/versions/3.8.5/lib/python3.8/site-packages (from requests>=2.23.0->catt==0.12.0) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in ./.pyenv/versions/3.8.5/lib/python3.8/site-packages (from requests>=2.23.0->catt==0.12.0) (2.10)
Using legacy 'setup.py install' for catt, since package 'wheel' is not installed.
Installing collected packages: PyChromecast, catt
    Running setup.py install for catt ... done
Successfully installed PyChromecast-8.1.2 catt-0.12.0
```

```
pip show catt
Name: catt
Version: 0.12.0
Summary: Cast All The Things allows you to send videos from many, many online sources to your Chromecast.
Home-page: https://github.com/skorokithakis/catt
Author: Stavros Korokithakis
Author-email: hi@stavros.io
License: BSD
Location: /Users/francois/.pyenv/versions/3.8.5/lib/python3.8/site-packages
Requires: youtube-dl, PyChromecast, Click, ifaddr, requests
Required-by:
```

```
pip show pychromecast
Name: PyChromecast
Version: 8.1.2
Summary: Python module to talk to Google Chromecast.
Home-page: https://github.com/balloob/pychromecast
Author: Paulus Schoutsen
Author-email: paulus@paulusschoutsen.nl
License: MIT
Location: /Users/francois/.pyenv/versions/3.8.5/lib/python3.8/site-packages
Requires: zeroconf, protobuf, casttube
Required-by: catt
```

```
catt scan
Scanning Chromecasts...
192.168.1.127 - Living Room TV - Google Inc. Chromecast
```

**Comment by borwolf** [comment]
Install PyChromecast 8.1.2 instead of latest 9.0.0. for me seems to solved the problem.

**Comment by skorokithakis** [comment]
0.12.1 has been released with a fix.

**Comment by borwolf** [comment]
Thank you skorokithakis.  0.12.1 indeed solved the problem.

**Comment by scooper1** [comment]
Fix ok for me thanks
