### ISSUE TITLE
catt scan fails with "No buffer space available"

### ISSUE THREAD

**Issue by EtienneM** [skorokithakis/catt#328]
```
╰─$ catt scan
Scanning Chromecasts...
Traceback (most recent call last):
  File "/home/titi/.local/bin/catt", line 8, in <module>
    sys.exit(main())
  File "/home/titi/.local/pipx/venvs/catt/lib/python3.8/site-packages/catt/cli.py", line 644, in main
    return cli(obj=get_config_as_dict())
  File "/home/titi/.local/pipx/venvs/catt/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/titi/.local/pipx/venvs/catt/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/titi/.local/pipx/venvs/catt/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/titi/.local/pipx/venvs/catt/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/titi/.local/pipx/venvs/catt/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/titi/.local/pipx/venvs/catt/lib/python3.8/site-packages/catt/cli.py", line 483, in scan
    devices = get_cast_devices_info()
  File "/home/titi/.local/pipx/venvs/catt/lib/python3.8/site-packages/catt/discovery.py", line 65, in get_cast_devices_info
    devices = get_cast_devices()
  File "/home/titi/.local/pipx/venvs/catt/lib/python3.8/site-packages/catt/discovery.py", line 47, in get_cast_devices
    cast_infos, browser = pychromecast.discovery.discover_chromecasts()
  File "/home/titi/.local/pipx/venvs/catt/lib/python3.8/site-packages/pychromecast/discovery.py", line 506, in discover_chromecasts
    zconf = zeroconf_instance or zeroconf.Zeroconf()
  File "/home/titi/.local/pipx/venvs/catt/lib/python3.8/site-packages/zeroconf/__init__.py", line 2493, in __init__
    self._listen_socket, self._respond_sockets = create_sockets(
  File "/home/titi/.local/pipx/venvs/catt/lib/python3.8/site-packages/zeroconf/__init__.py", line 2328, in create_sockets
    respond_socket = add_multicast_member(cast(socket.socket, listen_socket), i, apple_p2p=apple_p2p)
  File "/home/titi/.local/pipx/venvs/catt/lib/python3.8/site-packages/zeroconf/__init__.py", line 2273, in add_multicast_member
    listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 105] No buffer space available
```

This is the latest catt version:

```
╰─$ catt --version
catt v0.12.1, Zaniest Zapper.
```

I installed it with pipx. I have the same error if I install it with pip3.

**Comment by EtienneM** [comment]
I can see that  PyChromecast recently released a new version (https://github.com/home-assistant-libs/pychromecast/releases). Is it possible that it's what broke my installation? It used to work on a different laptop. The above-mentioned error is from a new installation

**Comment by skorokithakis** [comment]
Hmm, it's possible, can you try a previous version?

**Comment by EtienneM** [comment]
I just tried with PyChromecast 8.1.2 and catt 0.12.0 but I have the error :/

```
╰─$ pip3 install PyChromecast==8.1.2
Collecting PyChromecast==8.1.2
  Downloading PyChromecast-8.1.2-py2.py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB 398 kB/s 
Collecting zeroconf>=0.25.1
  Using cached zeroconf-0.28.8-py3-none-any.whl (55 kB)
Collecting casttube>=0.2.0
  Using cached casttube-0.2.1-py3-none-any.whl (6.5 kB)
Requirement already satisfied: protobuf>=3.0.0 in /usr/lib/python3/dist-packages (from PyChromecast==8.1.2) (3.6.1)
Collecting ifaddr>=0.1.7
  Using cached ifaddr-0.1.7-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from casttube>=0.2.0->PyChromecast==8.1.2) (2.22.0)
Installing collected packages: ifaddr, zeroconf, casttube, PyChromecast
Successfully installed PyChromecast-8.1.2 casttube-0.2.1 ifaddr-0.1.7 zeroconf-0.28.8

╰─$ pip3 install catt==0.12.0       
Collecting catt==0.12.0
  Using cached catt-0.12.0-py2.py3-none-any.whl (26 kB)
Collecting requests>=2.23.0
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting Click>=7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Requirement already satisfied: ifaddr>=0.1.7 in /home/titi/.local/lib/python3.8/site-packages (from catt==0.12.0) (0.1.7)
Collecting youtube-dl>=2020.9.20
  Using cached youtube_dl-2021.3.14-py2.py3-none-any.whl (1.9 MB)
Requirement already satisfied: PyChromecast>=7.5.0 in /home/titi/.local/lib/python3.8/site-packages (from catt==0.12.0) (8.1.2)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.23.0->catt==0.12.0) (2.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.23.0->catt==0.12.0) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.23.0->catt==0.12.0) (2019.11.28)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/lib/python3/dist-packages (from requests>=2.23.0->catt==0.12.0) (3.0.4)
Requirement already satisfied: protobuf>=3.0.0 in /usr/lib/python3/dist-packages (from PyChromecast>=7.5.0->catt==0.12.0) (3.6.1)
Requirement already satisfied: casttube>=0.2.0 in /home/titi/.local/lib/python3.8/site-packages (from PyChromecast>=7.5.0->catt==0.12.0) (0.2.1)
Requirement already satisfied: zeroconf>=0.25.1 in /home/titi/.local/lib/python3.8/site-packages (from PyChromecast>=7.5.0->catt==0.12.0) (0.28.8)
Installing collected packages: requests, Click, youtube-dl, catt
Successfully installed Click-7.1.2 catt-0.12.0 requests-2.25.1 youtube-dl-2021.3.14
```

**Comment by skorokithakis** [comment]
Still "No buffer space available"?

**Comment by EtienneM** [comment]
Yes indeed:
```
╰─$ ll ~/.local/lib/python3.8/site-packages/
total 64K
drwxrwxr-x 3 me me 4.0K Mar 19 21:29 casttube
drwxrwxr-x 2 me me 4.0K Mar 19 21:29 casttube-0.2.1.dist-info
drwxrwxr-x 3 me me 4.0K Mar 19 21:29 catt
drwxrwxr-x 2 me me 4.0K Mar 19 21:29 catt-0.12.0.dist-info
drwxrwxr-x 3 me me 4.0K Mar 19 21:29 click
drwxrwxr-x 2 me me 4.0K Mar 19 21:29 click-7.1.2.dist-info
drwxrwxr-x 3 me me 4.0K Mar 19 21:29 ifaddr
drwxrwxr-x 2 me me 4.0K Mar 19 21:29 ifaddr-0.1.7.dist-info
drwxrwxr-x 4 me me 4.0K Mar 19 21:29 pychromecast
drwxrwxr-x 2 me me 4.0K Mar 19 21:29 PyChromecast-8.1.2.dist-info
drwxrwxr-x 3 me me 4.0K Mar 19 21:29 requests
drwxrwxr-x 2 me me 4.0K Mar 19 21:29 requests-2.25.1.dist-info
drwxrwxr-x 6 me me 4.0K Mar 19 21:29 youtube_dl
drwxrwxr-x 2 me me 4.0K Mar 19 21:29 youtube_dl-2021.3.14.dist-info
drwxrwxr-x 3 me me 4.0K Mar 19 21:29 zeroconf
drwxrwxr-x 2 me me 4.0K Mar 19 21:29 zeroconf-0.28.8.dist-info

╰─$ catt scan
Scanning Chromecasts...
Traceback (most recent call last):
  File "/home/titi/.local/bin/catt", line 8, in <module>
    sys.exit(main())
  File "/home/titi/.local/lib/python3.8/site-packages/catt/cli.py", line 641, in main
    return cli(obj=get_config_as_dict())
  File "/home/titi/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/titi/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/titi/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/titi/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/titi/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/titi/.local/lib/python3.8/site-packages/catt/cli.py", line 482, in scan
    devices = get_cast_devices_info()
  File "/home/titi/.local/lib/python3.8/site-packages/catt/discovery.py", line 63, in get_cast_devices_info
    devices = get_cast_devices()
  File "/home/titi/.local/lib/python3.8/site-packages/catt/discovery.py", line 47, in get_cast_devices
    services, browser = pychromecast.discovery.discover_chromecasts()
  File "/home/titi/.local/lib/python3.8/site-packages/pychromecast/discovery.py", line 184, in discover_chromecasts
    zconf = zeroconf_instance or zeroconf.Zeroconf()
  File "/home/titi/.local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2493, in __init__
    self._listen_socket, self._respond_sockets = create_sockets(
  File "/home/titi/.local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2328, in create_sockets
    respond_socket = add_multicast_member(cast(socket.socket, listen_socket), i, apple_p2p=apple_p2p)
  File "/home/titi/.local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2273, in add_multicast_member
    listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 105] No buffer space available
```

**Comment by skorokithakis** [comment]
This looks like a PyChromecast bug, I'm afraid...

**Comment by EtienneM** [comment]
OK I'll try to open an issue there, thanks :)

**Comment by skorokithakis** [comment]
No problem!

**Comment by fivestones** [comment]
I had the same problem, and followed the instructions [here](https://blog.mphomphego.co.za/blog/2017/06/28/why-am-i-getting-errno105-no-buffer-space-available-when-subscribing-to-multicast-addresses.html#:~:text=The%20%22Errno%20105%22%20in%20this,groups%20at%20the%20same%20time.) for editing /etc/sysctl.conf. Just added the following to the end of the file: 

```# Bigger buffers (to make 40Gb more practical). These are maximums, but the default is unaffected.
net.core.wmem_max=268435456
net.core.rmem_max=268435456
net.core.netdev_max_backlog=10000

# Avoids problems with multicast traffic arriving on non-default interfaces
net.ipv4.conf.default.rp_filter=0
net.ipv4.conf.all.rp_filter=0

# Force IGMP v2 (required by CBF switch)
net.ipv4.conf.all.force_igmp_version=2
net.ipv4.conf.default.force_igmp_version=2

# Increase the ARP cache table
net.ipv4.neigh.default.gc_thresh3=4096
net.ipv4.neigh.default.gc_thresh2=2048
net.ipv4.neigh.default.gc_thresh1=1024

# Increase number of multicast groups permitted
net.ipv4.igmp_max_memberships=1024
```

Then `sudo sysctl -p` and that's it. No more buffer space available issues when running `catt scan`

**Comment by joelis10** [comment]
I know it's been a couple years, but where exactly did you edit the file? in the container or on the server?
