### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by wtrbuit** [skorokithakis/catt#362]
Hi,

I am new to the project and followed the steps to install catt on a raspberry pi. When I run the scan command I get this response:

```
Traceback (most recent call last):
  File "/usr/local/bin/catt", line 7, in <module>
    from catt.cli import main
  File "/home/pi/.local/lib/python3.5/site-packages/catt/cli.py", line 14, in <module>
    from .controllers import CastState
  File "/home/pi/.local/lib/python3.5/site-packages/catt/controllers.py", line 8, in <module>
    import pychromecast
  File "/home/pi/.local/lib/python3.5/site-packages/pychromecast/__init__.py", line 15, in <module>
    from .discovery import (  # noqa: F401
  File "/home/pi/.local/lib/python3.5/site-packages/pychromecast/discovery.py", line 366
    name = f"{host}:{port}"
                          ^
SyntaxError: invalid syntax
```

Can someone help me?

**Comment by skorokithakis** [comment]
You have a PyChromecast version that won't run under Python 3.5, you need 3.6 or later. This is also not a catt issue, it's a PyChromecast issue.
