### ISSUE TITLE
No buffer space available ??

### ISSUE THREAD

**Issue by CJA85** [skorokithakis/catt#363]
```
root@Nimbus:~/.local# catt scan
Scanning Chromecasts...
Traceback (most recent call last):
  File "/root/.local/bin/catt", line 8, in <module>
    sys.exit(main())
  File "/root/.local/pipx/venvs/catt/lib/python3.9/site-packages/catt/cli.py", l                                                           ine 644, in main
    return cli(obj=get_config_as_dict())
  File "/root/.local/pipx/venvs/catt/lib/python3.9/site-packages/click/core.py",                                                            line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/pipx/venvs/catt/lib/python3.9/site-packages/click/core.py",                                                            line 782, in main
    rv = self.invoke(ctx)
  File "/root/.local/pipx/venvs/catt/lib/python3.9/site-packages/click/core.py",                                                            line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/pipx/venvs/catt/lib/python3.9/site-packages/click/core.py",                                                            line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/pipx/venvs/catt/lib/python3.9/site-packages/click/core.py",                                                            line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/.local/pipx/venvs/catt/lib/python3.9/site-packages/catt/cli.py", l                                                           ine 483, in scan
    devices = get_cast_devices_info()
  File "/root/.local/pipx/venvs/catt/lib/python3.9/site-packages/catt/discovery.                                                           py", line 65, in get_cast_devices_info
    devices = get_cast_devices()
  File "/root/.local/pipx/venvs/catt/lib/python3.9/site-packages/catt/discovery.                                                           py", line 47, in get_cast_devices
    cast_infos, browser = pychromecast.discovery.discover_chromecasts()
  File "/root/.local/pipx/venvs/catt/lib/python3.9/site-packages/pychromecast/di                                                           scovery.py", line 519, in discover_chromecasts
    zconf = zeroconf_instance or zeroconf.Zeroconf()
  File "/root/.local/pipx/venvs/catt/lib/python3.9/site-packages/zeroconf/__init                                                           __.py", line 2499, in __init__
    self._listen_socket, self._respond_sockets = create_sockets(
  File "/root/.local/pipx/venvs/catt/lib/python3.9/site-packages/zeroconf/__init                                                           __.py", line 2331, in create_sockets
    if add_multicast_member(cast(socket.socket, listen_socket), i):
  File "/root/.local/pipx/venvs/catt/lib/python3.9/site-packages/zeroconf/__init                                                           __.py", line 2261, in add_multicast_member
    listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value                                                           )
OSError: [Errno 105] No buffer space available
```

```
root@Nimbus:~/.local/bin# ls -all
total 32
drwxr-xr-x 2 root root 4096 Nov 18 10:23 .
drwx------ 6 root root 4096 Nov 18 10:21 ..
-rwxr-xr-x 1 root root 3459 Nov 18 10:15 activate-global-python-argcomplete
lrwxrwxrwx 1 root root   37 Nov 18 10:23 catt -> /root/.local/pipx/venvs/catt/bin/catt
-rwxr-xr-x 1 root root  206 Nov 18 10:15 pipx
-rwxr-xr-x 1 root root 2555 Nov 18 10:15 python-argcomplete-check-easy-install-script
-rwxr-xr-x 1 root root  383 Nov 18 10:15 python-argcomplete-tcsh
-rwxr-xr-x 1 root root 1917 Nov 18 10:15 register-python-argcomplete
-rwxr-xr-x 1 root root  219 Nov 18 10:15 userpath
```

**Comment by CJA85** [comment]
```
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

Python 3.9.2
```

**Comment by CJA85** [comment]
Issue started after upgrading from Debian 10 Buster to Debian 11 Bullseye.

Have reinstalled catt, pip, pipx, pip3 to no help.

**Comment by skorokithakis** [comment]
This seems like an OS issue, as catt isn't doing anything special here. I'd try searching the web for some solutions, I'm afraid there isn't much we can do on our end.

**Comment by CJA85** [comment]
If someone else get this issue, here is the fix.

The solution is to tune your kerne. First things first we need to backup our current sysclt.conf and replace the contents with the ones below.
$ sudo nano /etc/sysctl.conf


```
# Bigger buffers (to make 40Gb more practical). These are maximums, but the default is unaffected.
net.core.wmem_max=268435456
net.core.rmem_max=268435456
net.core.netdev_max_backlog=10000

# Avoids problems with multicast traffic arriving on non-default interfaces
net.ipv4.conf.default.rp_filter=0
net.ipv4.conf.all.rp_filter=0

# Force IGMP v2 (required by CBF switch)
net.ipv4.conf.all.force_igmp_version=2
net.ipv4.conf.default.force_igmp_version=2

# Increase the ARP cache table
net.ipv4.neigh.default.gc_thresh3=4096
net.ipv4.neigh.default.gc_thresh2=2048
net.ipv4.neigh.default.gc_thresh1=1024

# Increase number of multicast groups permitted
net.ipv4.igmp_max_memberships=1024
```

After you have edited the file, you need to either reload the configuration file by executing, sudo sysctl -p or by rebooting your system.

At this point you are pretty much Done.

**Comment by skorokithakis** [comment]
Thanks for this! Though it's very odd that this would be necessary, I would have thought that Debian ships with good defaults already...
