### ISSUE TITLE
Catt scan fails 

### ISSUE THREAD

**Issue by hessius** [skorokithakis/catt#368]
After installing Catt and separately installing YouTube-dl (#367) I get the following error when running Catt scan

```
Traceback (most recent call last):

  File "/home/pi/.local/bin/catt", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/catt/cli.py", line 643, in main
    return cli(obj=get_config_as_dict())
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1656, in invoke
    super().invoke(ctx)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/catt/cli.py", line 141, in cli
    ctx.obj["selected_device"] = process_device(device or device_from_config, ctx.obj["aliases"])
  File "/home/pi/.local/lib/python3.7/site-packages/catt/cli.py", line 113, in process_device
    return aliases.get(device_desc.lower(), device_desc)

AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by skorokithakis** [comment]
Ah, damn, this is related to the new alias code. Will fix ASAP, thank you.
