### ISSUE TITLE
catt errors on Python 3.10 (Arch)

### ISSUE THREAD

**Issue by weisserd** [skorokithakis/catt#373]
When trying any subcommand with `catt` (e.g. `scan` or `cast_site`) I get the following error:

```bash
$ catt scan
Scanning Chromecasts...
Traceback (most recent call last):
  File "/usr/bin/catt", line 33, in <module>
    sys.exit(load_entry_point('catt==0.12.1', 'console_scripts', 'catt')())
  File "/usr/lib/python3.10/site-packages/catt/cli.py", line 644, in main
    return cli(obj=get_config_as_dict())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/catt/cli.py", line 483, in scan
    devices = get_cast_devices_info()
  File "/usr/lib/python3.10/site-packages/catt/discovery.py", line 65, in get_cast_devices_info
    devices = get_cast_devices()
  File "/usr/lib/python3.10/site-packages/catt/discovery.py", line 50, in get_cast_devices
    devices = [
  File "/usr/lib/python3.10/site-packages/catt/discovery.py", line 51, in <listcomp>
    CastDevice(pychromecast.get_chromecast_from_cast_info(c, browser.zc), c.host, c.port) for c in cast_infos
  File "/usr/lib/python3.10/site-packages/pychromecast/__init__.py", line 69, in get_chromecast_from_cast_info
    return Chromecast(
  File "/usr/lib/python3.10/site-packages/pychromecast/__init__.py", line 272, in __init__
    cast_info = get_cast_type(cast_info, zconf)
  File "/usr/lib/python3.10/site-packages/pychromecast/dial.py", line 121, in get_cast_type
    status = _get_status(
  File "/usr/lib/python3.10/site-packages/pychromecast/dial.py", line 78, in _get_status
    host, _, _ = get_host_from_service(service, zconf)
  File "/usr/lib/python3.10/site-packages/pychromecast/dial.py", line 38, in get_host_from_service
    service_info = zconf.get_service_info("_googlecast._tcp.local.", service.data)
  File "/usr/lib/python3.10/site-packages/zeroconf/_core.py", line 523, in get_service_info
    if info.request(self, timeout, question_type):
  File "/usr/lib/python3.10/site-packages/zeroconf/_services/info.py", line 455, in request
    assert zc.loop is not None and zc.loop.is_running()
AssertionError
```

The versions used are:
* Python 3.10.1
* catt v0.12.1, Zaniest Zapper.
* OS ManjaroLinux - catt installed from aur - https://aur.archlinux.org/packages/catt/

**Comment by weisserd** [comment]
Looks similar to the already closed issue #349

**Comment by skorokithakis** [comment]
Yes, sounds like the same bug, can you try the latest version and see if that solves it?

**Comment by weisserd** [comment]
When switiching to catt-git (https://aur.archlinux.org/packages/catt-git) it reports the following version:
* catt v0.12.5, Zaniest Zapper.

However the problem still exists - its the same stacktrace as above

**Comment by skorokithakis** [comment]
Hmm, what's the PyChromecast version?

**Comment by weisserd** [comment]
It's `aur/python-pychromecast 10.2.2-1`

**Comment by skorokithakis** [comment]
That's the wrong version, please either use one of the supported methods of installation or file a bug with AUR.

**Comment by juxuanu** [comment]
@skorokithakis I am having the same issue. What is the required `python-pychromecast` version?
