### ISSUE TITLE
Error when trying to cast

### ISSUE THREAD

**Issue by K4LCIFER** [skorokithakis/catt#385]
when running `catt cast '<path-to-video>'`, I get the following output:
```
Traceback (most recent call last):
  File "/usr/bin/catt", line 33, in <module>
    sys.exit(load_entry_point('catt==0.12.1', 'console_scripts', 'catt')())
  File "/usr/lib/python3.10/site-packages/catt/cli.py", line 644, in main
    return cli(obj=get_config_as_dict())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/catt/cli.py", line 219, in cast
    cst, stream = setup_cast(
  File "/usr/lib/python3.10/site-packages/catt/controllers.py", line 78, in setup_cast
    cast_device = get_cast_device(device_desc)
  File "/usr/lib/python3.10/site-packages/catt/discovery.py", line 135, in get_cast_device
    cast_device = get_cast_device_with_name(device_desc)
  File "/usr/lib/python3.10/site-packages/catt/discovery.py", line 80, in get_cast_device_with_name
    devices = get_cast_devices([device_name]) if device_name else get_cast_devices()
  File "/usr/lib/python3.10/site-packages/catt/discovery.py", line 50, in get_cast_devices
    devices = [
  File "/usr/lib/python3.10/site-packages/catt/discovery.py", line 51, in <listcomp>
    CastDevice(pychromecast.get_chromecast_from_cast_info(c, browser.zc), c.host, c.port) for c in cast_infos
  File "/usr/lib/python3.10/site-packages/pychromecast/__init__.py", line 69, in get_chromecast_from_cast_info
    return Chromecast(
  File "/usr/lib/python3.10/site-packages/pychromecast/__init__.py", line 272, in __init__
    cast_info = get_cast_type(cast_info, zconf)
  File "/usr/lib/python3.10/site-packages/pychromecast/dial.py", line 121, in get_cast_type
    status = _get_status(
  File "/usr/lib/python3.10/site-packages/pychromecast/dial.py", line 78, in _get_status
    host, _, _ = get_host_from_service(service, zconf)
  File "/usr/lib/python3.10/site-packages/pychromecast/dial.py", line 38, in get_host_from_service
    service_info = zconf.get_service_info("_googlecast._tcp.local.", service.data)
  File "/usr/lib/python3.10/site-packages/zeroconf/_core.py", line 533, in get_service_info
    if info.request(self, timeout, question_type):
  File "/usr/lib/python3.10/site-packages/zeroconf/_services/info.py", line 459, in request
    assert zc.loop is not None and zc.loop.is_running()
AssertionError

```

**Comment by Emgalai** [comment]
I get the same error. And similar error also comes with `catt scan`

```
  File "/usr/bin/catt", line 33, in <module>
    sys.exit(load_entry_point('catt==0.12.7', 'console_scripts', 'catt')())
  File "/usr/lib/python3.10/site-packages/catt/cli.py", line 660, in main
    return cli(obj=get_config_as_dict())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/catt/cli.py", line 496, in scan
    devices = get_cast_devices_info()
  File "/usr/lib/python3.10/site-packages/catt/discovery.py", line 65, in get_cast_devices_info
    devices = get_cast_devices()
  File "/usr/lib/python3.10/site-packages/catt/discovery.py", line 50, in get_cast_devices
    devices = [
  File "/usr/lib/python3.10/site-packages/catt/discovery.py", line 51, in <listcomp>
    CastDevice(pychromecast.get_chromecast_from_cast_info(c, browser.zc), c.host, c.port) for c in cast_infos
  File "/usr/lib/python3.10/site-packages/pychromecast/__init__.py", line 69, in get_chromecast_from_cast_info
    return Chromecast(
  File "/usr/lib/python3.10/site-packages/pychromecast/__init__.py", line 272, in __init__
    cast_info = get_cast_type(cast_info, zconf)
  File "/usr/lib/python3.10/site-packages/pychromecast/dial.py", line 121, in get_cast_type
    status = _get_status(
  File "/usr/lib/python3.10/site-packages/pychromecast/dial.py", line 78, in _get_status
    host, _, _ = get_host_from_service(service, zconf)
  File "/usr/lib/python3.10/site-packages/pychromecast/dial.py", line 38, in get_host_from_service
    service_info = zconf.get_service_info("_googlecast._tcp.local.", service.data)
  File "/usr/lib/python3.10/site-packages/zeroconf/_core.py", line 533, in get_service_info
    if info.request(self, timeout, question_type):
  File "/usr/lib/python3.10/site-packages/zeroconf/_services/info.py", line 459, in request
    assert zc.loop is not None and zc.loop.is_running()
AssertionError
```

**Comment by Emgalai** [comment]
I tried this example script from pychromecast and it finds my Chromecast
https://github.com/home-assistant-libs/pychromecast/blob/master/examples/discovery_example2.py

**Comment by Emgalai** [comment]
This is the error I get if I try with the `-d` option:

$ catt -d 192.168.0.14 cast https://www.youtube.com/watch?v=F7V8DRfZBQI
```
Traceback (most recent call last):
  File "/usr/bin/catt", line 33, in <module>
    sys.exit(load_entry_point('catt==0.12.7', 'console_scripts', 'catt')())
  File "/usr/lib/python3.10/site-packages/catt/cli.py", line 660, in main
    return cli(obj=get_config_as_dict())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/catt/cli.py", line 232, in cast
    cst, stream = setup_cast(
  File "/usr/lib/python3.10/site-packages/catt/controllers.py", line 78, in setup_cast
    cast_device = get_cast_device(device_desc)
  File "/usr/lib/python3.10/site-packages/catt/discovery.py", line 130, in get_cast_device
    cast_device = get_cast_device_with_ip(device_desc, DEFAULT_PORT)
  File "/usr/lib/python3.10/site-packages/catt/discovery.py", line 98, in get_cast_device_with_ip
    cast = pychromecast.Chromecast(device_ip, port=port, tries=1)
TypeError: Chromecast.__init__() got an unexpected keyword argument 'port'
```

**Comment by skorokithakis** [comment]
Sounds like CATT hasn't been installed correctly, try reinstalling it.

**Comment by Emgalai** [comment]
Seems there is something wrong with the [AUR PKGBUILD](https://aur.archlinux.org/packages/catt-git) as installing catt with pipx works just fine. Sorry for not trying that before.

**Comment by theychx** [comment]
Closing, as this appears to be purely distro-related.
