### ISSUE TITLE
`catt==0.12.8` with `PyChromecast==12.1.4` fails with a `TypeError`

### ISSUE THREAD

**Issue by alexdelorenzo** [skorokithakis/catt#402]
Here's the example using the latest `catt` with the latest `PyChromecast`:
```bash
$ catt -d $(dig +short chromecast.lan) cast "https://www.youtube.com/watch?v=YzuvMHvQiiA"
```
 ```python3
Traceback (most recent call last):                                                                                                                                                                                                  
  File "~/.local/lib/python3.9/site-packages/catt/cli.py", line 232, in cast                                       
    cst, stream = setup_cast( 
  File "~/.local/lib/python3.9/site-packages/catt/controllers.py", line 78, in setup_cast
    cast = get_cast(device_desc) 
  File "~/.local/lib/python3.9/site-packages/catt/discovery.py", line 111, in get_cast                                                  
    cast = get_cast_with_ip(cast_desc, DEFAULT_PORT)                    
  File "~/.local/lib/python3.9/site-packages/catt/discovery.py", line 79, in get_cast_with_ip
    cast = pychromecast.Chromecast(cast_ip, port=port, tries=1)
TypeError: __init__() got an unexpected keyword argument 'port'
```
After the 9.x releases of PyChromecast, `pychromecast.Chromecast` doesn't take a `port` argument anymore. 

Downgrading PyChromecast fails with Catt, because newer versions of Catt use PyChromecast's updated API elsewhere.

The last Catt version I got working is `catt==0.12.2` with `PyChromecast==9.2.0`. Versions of Catt above 0.12.2 that depend on newer PyChromecast versions would fail, as well.

As an aside, I have a couple of projects built against PyChromecast, and while it is an excellent library, in my experience, semantic versioning isn't always followed by the project. 
I found the need to pin PyChromecast to major release versions, and sometimes to specific point releases, because the project will sometimes make breaking API changes in minor version bumps.

**Comment by alexdelorenzo** [comment]
Should also mention that I'm encountering this problem on the last two Ubuntu LTS releases, and Arch, using both system Python installations along with local installations via `pyenv`.
