### ISSUE TITLE
Import Errors - ImportError: dlopen()

### ISSUE THREAD

**Issue by cburgdorfer** [skorokithakis/catt#417]
Hello,

I've just installed CATT via pipx on a brand new M1 Mac right off a reset. I get this error:

```
johndoe@Johns-Mac-mini-M1 ~ % catt
Traceback (most recent call last):
  File "/Users/johndoe/.local/bin/catt", line 5, in <module>
    from catt.cli import main
  File "/Users/johndoe/.local/pipx/venvs/catt/lib/python3.10/site-packages/catt/cli.py", line 19, in <module>
    from .controllers import CastState
  File "/Users/johndoe/.local/pipx/venvs/catt/lib/python3.10/site-packages/catt/controllers.py", line 8, in <module>
    import pychromecast
  File "/Users/johndoe/.local/pipx/venvs/catt/lib/python3.10/site-packages/pychromecast/__init__.py", line 14, in <module>
    from . import socket_client
  File "/Users/johndoe/.local/pipx/venvs/catt/lib/python3.10/site-packages/pychromecast/socket_client.py", line 23, in <module>
    from . import cast_channel_pb2
  File "/Users/johndoe/.local/pipx/venvs/catt/lib/python3.10/site-packages/pychromecast/cast_channel_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Users/johndoe/.local/pipx/venvs/catt/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: dlopen(/Users/johndoe/.local/pipx/venvs/catt/lib/python3.10/site-packages/google/protobuf/pyext/_message.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (__ZN6google8protobuf15FieldDescriptor12TypeOnceInitEPKS1_)
johndoe@Johns-Mac-mini-M1 ~ % 
```

I should have Python3:

```
brew install python3
Warning: python@3.10 3.10.7 is already installed and up-to-date.
To reinstall 3.10.7, run:
  brew reinstall python@3.10
```

Do you have any suggestion where I was going wrong? 

Thanks a lot for your help! Much appreciated!

**Comment by skorokithakis** [comment]
Hm, it looks like a protobuf issue on the M1 perhaps? I think the protobuf repo would be the place to file the issue, as it doesn't seem directly related to catt.
