### ISSUE TITLE
API example dont run

### ISSUE THREAD

**Issue by GrLinkDn** [skorokithakis/catt#450]
I use the example to understand how can i use API.
When i start example py i receive this:

```
Traceback (most recent call last):
  File "/root/chromecast/chromecast-venv/lib/python3.11/site-packages/catt/stream_info.py", line 197, in _get_stream_url
    best_format = next(format_selector(info))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/chromecast/prova2.py", line 20, in <module>
    ouch(sys.argv[1])
  File "/root/chromecast/prova2.py", line 15, in ouch
    cast.play_url(video, resolve=True, block=True)
  File "/root/chromecast/chromecast-venv/lib/python3.11/site-packages/catt/api.py", line 86, in play_url
    url = stream.video_url
          ^^^^^^^^^^^^^^^^
  File "/root/chromecast/chromecast-venv/lib/python3.11/site-packages/catt/stream_info.py", line 111, in video_url
    return self._get_stream_url(self._info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chromecast/chromecast-venv/lib/python3.11/site-packages/catt/stream_info.py", line 199, in _get_stream_url
    raise FormatError("No suitable format was found")
catt.error.FormatError: No suitable format was found

```

**Comment by evandrofisico** [comment]
Same thing here, python 3.12, trying to use the examples (with the latest yt-dlp installed) i get this

> evandro@sekhmet:~/Trabalho/Avulsos/Mytube$ uv run catt/examples/accidents.py
> Traceback (most recent call last):
>   File "/home/evandro/Trabalho/Avulsos/Mytube/catt/examples/accidents.py", line 20, in <module>
>     ouch()
>   File "/home/evandro/Trabalho/Avulsos/Mytube/catt/examples/accidents.py", line 15, in ouch
>     cast.play_url(video, resolve=True, block=True)
>   File "/home/evandro/Trabalho/Avulsos/Mytube/.venv/lib/python3.12/site-packages/catt/api.py", line 98, in play_url
>     raise APIError("Playback failed")
> catt.error.APIError: Playback failed
