### ISSUE TITLE
Can't assign requested address

### ISSUE THREAD

**Issue by dalanmiller** [skorokithakis/catt#99]
Does `catt` need to be run as root? Wasn't able to get this successfully running after install. Happy to provide more info! 

```
$ catt -d RevTV cast ~/Downloads/VID_20180308_085122.mp4

Traceback (most recent call last):
  File "/usr/local/bin/catt", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/catt/cli.py", line 381, in main
    return cli(obj={}, default_map=readconfig())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/catt/cli.py", line 116, in cast
    prep="app", controller=controller)
  File "/usr/local/lib/python3.6/site-packages/catt/controllers.py", line 84, in setup_cast
    stream = StreamInfo(video_url, model=cc_info, host=cast.host)
  File "/usr/local/lib/python3.6/site-packages/catt/stream_info.py", line 32, in __init__
    self.local_ip = self._get_local_ip(host)
  File "/usr/local/lib/python3.6/site-packages/catt/stream_info.py", line 154, in _get_local_ip
    sock.connect((cc_host, 0))
OSError: [Errno 49] Can't assign requested address
```

**Comment by skorokithakis** [comment]
Ah yes, thanks for the report, I'm getting the same issue and have been meaning to fix it. Will get on that, thank you!

**Comment by theychx** [comment]
I can't reproduce this. Is it because we are trying to use a port that is already in use?

**Comment by skorokithakis** [comment]
I don't think so, my desktop could reproduce it pretty consistently. I'll do some testing when I'm home, as I'm in Rome for the weekend.

**Comment by theychx** [comment]
Strike that, I misread the traceback.

**Comment by theychx** [comment]
My educated guess would be that this is ipv6 related. If this is the case, I think we should consider using ```netifaces``` (already pulled in by ```pychromcast -> zeroconf```) to find the local ip-address.

**Comment by skorokithakis** [comment]
It might be, but if I remember correctly I tried to print the address it was finding and it was the right IPv4 one. I'll double-check, though.

**Comment by echaouchna** [comment]
Just tried your branch, it works

**Comment by skorokithakis** [comment]
Fantastic, I'll try it as well and merge if it works for me too. Unfortunately, it'll have to be on Tuesday 🙁

**Comment by skorokithakis** [comment]
@theychx can you make a pr?
